YOOVIS/routes/web.php
<?php

use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\Controller;
use App\Http\Controllers\KerusakanhpController;
use App\Http\Controllers\TransactionController;
use App\Http\Controllers\DashboardController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use PhpParser\Node\Expr\AssignOp\Concat;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend.home');
})->name('user.home');

Route::get('/service-smartphone', [TransactionController::class, 'serviceHp'])->name('service-smartphone');
Route::post('/service-smartphone', [TransactionController::class, 'transactionHp'])->name('transaksi.hp');
Route::get('/service-laptop', [TransactionController::class, 'serviceLaptop'])->name('service-laptop');
Route::post('/service-laptop', [TransactionController::class, 'transactionLaptop'])->name('transaksi.laptop');
Route::get('/service-printer', [TransactionController::class, 'servicePrinter'])->name('service-printer');
Route::post('/service-printer', [TransactionController::class, 'transactionPrinter'])->name('transaksi.printer');


Route::get('/checkout/{id}', [CheckoutController::class, 'index'])->name('checkout.index');
Route::put('/checkout/{id}', [CheckoutController::class, 'update'])->name('checkout.update');
Route::get('/keranjang', [TransactionController::class, 'keranjang'])->name('transaction.keranjang');

Route::resource('profileuser', 'ProfileuserController');

Route::get('/user', function () {
    return view('frontend.home');
})->name('user');

Auth::routes();
// route dengan prefix admin
Route::group(['prefix' => 'admin', 'middleware' => ['roleAdmin']], function () {
    // route dengan role admin
    Route::get('/', [App\Http\Controllers\DashboardController::class, 'index'])->name('home');
    Route::resource('/category', 'CategoryController', ['as' => 'admin']);
    Route::resource('/kerusakan', 'KerusakanController', ['as' => 'admin']);
    Route::get('/transaction', [App\Http\Controllers\TransactionController::class, 'index'])->name('admin.transaction.index');
    Route::post('/transaction/{transaction}', [App\Http\Controllers\TransactionController::class, 'destroy'])->name('admin.transaction.destroy');
    Route::resource('/barang', 'BarangController', ['as' => 'admin']);
    Route::resource('/pengguna', 'PenggunaController', ['as' => 'admin']);
    Route::resource('/kerusakanhp', 'KerusakanhpController', ['as' => 'admin']);
    Route::resource('/kerusakanlaptop', 'KerusakanlaptopController', ['as' => 'admin']);
    Route::resource('/kerusakanprinter', 'KerusakanprinterController', ['as' => 'admin']);
    Route::get('/profile', [App\Http\Controllers\HomeController::class, 'profile'])->name('admin.profile.index');
});

YOOVIS/app/Models/profileuser.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class profileuser extends Model
{
    use HasFactory;
    protected $table = "users";
    protected $primaryKey = 'id';
    protected $fillable = [
        'name',
        'username',
        'email',
    ];
}

YOOVIS/app/Http/Controllers/ProfileuserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\profileuser;
use Illuminate\Support\Facades\DB;

class ProfileuserController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $profileuser = DB::table('users')->first();
        return view('frontend/profileuser.index', compact('profileuser'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        { 
            $profileuser = DB::table('users')->first();
            $admin_lecturer = "Menambahkan";
            return view('frontend/profileuser.create', compact('profileuser','admin_lecturer'));
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        DB::table('users')->insert([
            'name' => $request->name,
            'username' => $request->username,
            'email' => $request->email,
            'role' => $request->role,
        ]);
        return redirect()->route('profileuser.index')
            ->with('success','Data berhasil ditambahkan.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
            $profileuser = Profileuser::where('id', $id)->first();
            $admin_lecturer = "Mengubah";
            return view('frontend/profileuser.create', compact('users','admin_lecturer'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function update(Request $request, $id)
    {
        $profileuser = Profileuser::find($request->id);
        $profileuser->name = $request->name;
        // $profileuser->username = $request->username;
        // $profileuser->email = $request->email;
        // $profileuser->role = $request->role;
        $profileuser->save();
        return redirect()->route('profileuser.index')
                        ->with('success','Data berhasil diperbaharui.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Profileuser $profileuser)
    {
        // $kerusakanhp->delete();
        // return redirect()->route('kerusakanhp.index')
        //                 ->with('success','Data berhasil dihapus.');
    }
}

YOOVIS/resources/views/frontend/profileuser/create.blade.php
@extends('frontend/layouts.template')
@section('content')
<!--main content start-->

<div class="container">
<div class="page-wrapper">
  <!-- ============================================================== -->
  <!-- Bread crumb and right sidebar toggle -->
  <!-- ============================================================== -->
  <div class="page-breadcrumb">
      <div class="row align-items-center">
          <div class="col-md-6 col-8 align-self-center">
              <div class="d-flex align-items-center">
                  <nav aria-label="breadcrumb">
                      <ol class="breadcrumb">

                      </ol>
                  </nav>
              </div>
          </div>
      </div>
      <br><br><br>
      <div>
        <div class="service">
            <div class="title">

                Edit Profile User
            </div>
        </div>
      </div>
  </div>

  <br><br>
  <!-- ============================================================== -->
  <!-- End Bread crumb and right sidebar toggle -->
  <!-- ============================================================== -->
  <!-- ============================================================== -->
<!-- Container fluid  -->
            <!-- ============================================================== -->
            <div class="container-fluid">
                <!-- ============================================================== -->
                <!-- Start Page Content -->
                <!-- ============================================================== -->
                <!-- Row -->
                <div class="row">
                    <!-- Column -->
                    <div class="col-lg-4 col-xlg-3 col-md-5">
                        <div class="card">
                            <div class="card-body profile-card">
                                <center class="mt-4"> <img src="{{ asset('frontend/assets/img/profil.png')}}"
                                        class="rounded-circle" width="150" />
                                        <h4 class="card-title mt-2"></h4>

                                </center>
                            </div>
                        </div>
                    </div>
                    <!-- Column -->
                    <!-- Column -->
                    <div class="col-lg-8 col-xlg-9 col-md-7">
                        <div class="card">
                            <div class="card-body">
                                <!-- <div class="col-lg-8"> -->
                                    <form class="form-horizontal form-material mx-2" action="{{ isset($profileuser) ? route('profileuser.update',$profileuser->id) : route('profileuser.store') }}" method="POST">
                                    {!! csrf_field() !!}
                                    {!! isset($profileuser) ? method_field('PUT') : '' !!}
                                    <input type="hidden" name="id" value="{{ isset($profileuser) ? $profileuser->id : ''}}">
                                      <div class="form-group">
                                        <label for="cname" class="control-label col-lg-2">Nama</label>
                                        <div class="col-lg-12">
                                          <input class="form-control" type="text" name="name" id="name" minlenght="5" value="{{ isset($profileuser) ? $profileuser->name : ''}}" />
                                        </div>
                                      </div>
                                      <div class="form-group">
                                        <label for="cname" class="control-label col-lg-2">Username</label>
                                        <div class="col-lg-12">
                                          <input class="form-control" type="text" name="username" id="username" minlenght="5" value="{{ $profileuser->username }}" disabled/>
                                        </div>
                                      </div>
                                      <div class="form-group">
                                        <label for="cname" class="control-label col-lg-2">Email</label>
                                        <div class="col-lg-12">
                                          <input class="form-control" type="email" name="email" id="email" value="{{ $profileuser->email }}" disabled/>
                                        </div>
                                      </div>
                                      <div class="btn-group mt-3">
                                        <div class="col-lg-offset-2 col-lg-10">
                                        <button class="btn btn-primary" type="submit">Submit</button>
                                        <a href="{{ route('profileuser.index') }}"><button class="btn btn-default" type="button">Cancel</button></a>
                                        </div>
                                      </div>
                                    </form>
                                  <!-- </div> -->
                            </div>
                        </div>
                    </div>
                    <!-- Column -->
                </div>
                <!-- Row -->
                <!-- ============================================================== -->
                <!-- End PAge Content -->
                <!-- ============================================================== -->
                <!-- ============================================================== -->
                <!-- Right sidebar -->
                <!-- ============================================================== -->
                <!-- .right-sidebar -->
                <!-- ============================================================== -->
                <!-- End Right sidebar -->
                <!-- ============================================================== -->
            </div>
            <!-- ============================================================== -->
            <!-- End Container fluid  -->
  <!-- ============================================================== -->
  <!-- ============================================================== -->
</div>
<!-- ============================================================== -->
<!-- End Page wrapper  -->
</div>
@endsection

YOOVIS/resources/views/frontend/profileuser/index.blade.php
@extends('frontend/layouts.template')
@section('content')
<!--main content start-->

<div class="container">
<div class="page-wrapper">
  <!-- ============================================================== -->
  <!-- Bread crumb and right sidebar toggle -->
  <!-- ============================================================== -->
  <div class="page-breadcrumb">
      <div class="row align-items-center">
          <div class="col-md-6 col-8 align-self-center">
              <div class="d-flex align-items-center">
                  <nav aria-label="breadcrumb">
                      <ol class="breadcrumb">

                      </ol>
                  </nav>
              </div>
          </div>
      </div>
      <br><br><br>
      <div>
        <div class="service">
            <div class="title">

              Profile User
            </div>
        </div>
      </div>
  </div>

  <br><br>
  <!-- ============================================================== -->
  <!-- End Bread crumb and right sidebar toggle -->
  <!-- ============================================================== -->
  <!-- ============================================================== -->
<!-- Container fluid  -->
            <!-- ============================================================== -->
            <div class="container-fluid">
                <!-- ============================================================== -->
                <!-- Start Page Content -->
                <!-- ============================================================== -->
                <!-- Row -->
                <div class="row">
                    <!-- Column -->
                    <div class="col-lg-4 col-xlg-3 col-md-5">
                        <div class="card">
                            <div class="card-body profile-card">
                                <center class="mt-4"> <img src="{{ asset('frontend/assets/img/profil.png')}}"
                                        class="rounded-circle" width="150" />
                                        <h4 class="card-title mt-2">{{ $profileuser->name }}</h4>

                                </center>
                            </div>
                        </div>
                    </div>
                    <!-- Column -->
                    <!-- Column -->
                    <div class="col-lg-8 col-xlg-9 col-md-7">
                        <div class="card">
                            <div class="card-body">
                                <!-- <div class="col-lg-8"> -->
                                    <form class="form-horizontal form-material mx-2" method="post">
                                      <div class="form-group">
                                        <label for="cname" class="control-label col-lg-2">Nama</label>
                                        <div class="col-lg-12">
                                          <input class="form-control" type="text" name="name" id="name" minlenght="5" value="{{ $profileuser->name }}" disabled />
                                        </div>
                                      </div>
                                      <div class="form-group">
                                        <label for="cname" class="control-label col-lg-2">Username</label>
                                        <div class="col-lg-12">
                                          <input class="form-control" type="text" name="username" id="username" minlenght="5" value="{{ $profileuser->username }}" disabled/>
                                        </div>
                                      </div>
                                      <div class="form-group">
                                        <label for="cname" class="control-label col-lg-2">Email</label>
                                        <div class="col-lg-12">
                                          <input class="form-control" type="email" name="email" id="email" value="{{ $profileuser->email }}" disabled/>
                                        </div>
                                      </div>
                                      <div class="btn-group mt-3">
                                        <a href="{{url('/profileuser/create')}}" class="btn btn-primary">Edit</a>
                                      </div>
                                    </form>
                                  <!-- </div> -->
                            </div>
                        </div>
                    </div>
                    <!-- Column -->
                </div>
                <!-- Row -->
                <!-- ============================================================== -->
                <!-- End PAge Content -->
                <!-- ============================================================== -->
                <!-- ============================================================== -->
                <!-- Right sidebar -->
                <!-- ============================================================== -->
                <!-- .right-sidebar -->
                <!-- ============================================================== -->
                <!-- End Right sidebar -->
                <!-- ============================================================== -->
            </div>
            <!-- ============================================================== -->
            <!-- End Container fluid  -->
  <!-- ============================================================== -->
  <!-- ============================================================== -->
</div>
<!-- ============================================================== -->
<!-- End Page wrapper  -->
</div>
@endsection