YOOVIS/routes/web.php
<?php

use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\Controller;
use App\Http\Controllers\KerusakanhpController;
use App\Http\Controllers\TransactionController;
use App\Http\Controllers\DashboardController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use PhpParser\Node\Expr\AssignOp\Concat;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend.home');
})->name('user.home');

Route::get('/service-smartphone', [TransactionController::class, 'serviceHp'])->name('service-smartphone');
Route::post('/service-smartphone', [TransactionController::class, 'transactionHp'])->name('transaksi.hp');
Route::get('/service-laptop', [TransactionController::class, 'serviceLaptop'])->name('service-laptop');
Route::post('/service-laptop', [TransactionController::class, 'transactionLaptop'])->name('transaksi.laptop');
Route::get('/service-printer', [TransactionController::class, 'servicePrinter'])->name('service-printer');
Route::post('/service-printer', [TransactionController::class, 'transactionPrinter'])->name('transaksi.printer');


Route::get('/checkout/{id}', [CheckoutController::class, 'index'])->name('checkout.index');
Route::put('/checkout/{id}', [CheckoutController::class, 'update'])->name('checkout.update');
Route::get('/keranjang', [TransactionController::class, 'keranjang'])->name('transaction.keranjang');

Route::resource('profileuser', 'ProfileuserController');

Route::get('/user', function () {
    return view('frontend.home');
})->name('user');

Auth::routes();
// route dengan prefix admin
Route::group(['prefix' => 'admin', 'middleware' => ['roleAdmin']], function () {
    // route dengan role admin
    Route::get('/', [App\Http\Controllers\DashboardController::class, 'index'])->name('home');
    Route::resource('/category', 'CategoryController', ['as' => 'admin']);
    Route::resource('/kerusakan', 'KerusakanController', ['as' => 'admin']);
    Route::get('/transaction', [App\Http\Controllers\TransactionController::class, 'index'])->name('admin.transaction.index');
    Route::post('/transaction/{transaction}', [App\Http\Controllers\TransactionController::class, 'destroy'])->name('admin.transaction.destroy');
    Route::resource('/barang', 'BarangController', ['as' => 'admin']);
    Route::resource('/pengguna', 'PenggunaController', ['as' => 'admin']);
    Route::resource('/kerusakanhp', 'KerusakanhpController', ['as' => 'admin']);
    Route::resource('/kerusakanlaptop', 'KerusakanlaptopController', ['as' => 'admin']);
    Route::resource('/kerusakanprinter', 'KerusakanprinterController', ['as' => 'admin']);
    Route::get('/profile', [App\Http\Controllers\HomeController::class, 'profile'])->name('admin.profile.index');
});

YOOVIS/app/Models/Kerusakan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Kerusakan extends Model
{
    use HasFactory;
    protected $fillable = [
        'category_id',
        'jenis_kerusakan',
        'harga',
    ];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function transaction()
    {
        return $this->hasMany(Transaction::class);
    }
}

YOOVIS/app/Http/Controllers/KerusakanController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\Kerusakan;
use Illuminate\Http\Request;

class KerusakanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $kerusakan = Kerusakan::all();

        return view('backend.kerusakan.index', compact('kerusakan'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('backend.kerusakan.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'category_id'       => 'required',
            'jenis_kerusakan'   => 'required',
            'harga'             => 'required',
        ]);

        //save to DB
        $kerusakan = Kerusakan::create([
            'category_id'   => $request->category_id,
            'jenis_kerusakan' => $request->jenis_kerusakan,
            'harga'         => $request->harga,
        ]);

        if ($kerusakan) {
            //redirect dengan pesan sukses
            return redirect()->route('admin.kerusakan.index')->with(['success' => 'Data Berhasil Disimpan!']);
        } else {
            //redirect dengan pesan error
            return redirect()->route('admin.kerusakan.index')->with(['error' => 'Data Gagal Disimpan!']);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $kerusakan = Kerusakan::where('id', $id)->first();
        $categories = Category::all();
        return view('backend.kerusakan.create', compact('kerusakan', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $kerusakan = Kerusakan::find($request->id);
        //update data
        $kerusakan->update([
            'category_id'   => $request->category_id,
            'jenis_kerusakan' => $request->jenis_kerusakan,
            'harga'         => $request->harga,
        ]);

        if ($kerusakan) {
            //redirect dengan pesan sukses
            return redirect()->route('admin.kerusakan.index')->with(['success' => 'Data Berhasil Diperbarui!']);
        } else {
            //redirect dengan pesan error
            return redirect()->route('admin.kerusakan.index')->with(['error' => 'Data Gagal Diperbarui!']);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Kerusakan $kerusakan)
    {
        $kerusakan->delete();
        return redirect()->route('admin.kerusakan.index')
            ->with('success', 'Data Barang berhasil dihapus.');
    }
}

YOOVIS/resources/views/backend/kerusakan/create.blade.php
@extends('backend/layouts.template')
@section('content')
<!--main content start-->
<div class="page-wrapper">
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="page-breadcrumb">
        <div class="row align-items-center">
            <div class="col-md-6 col-8 align-self-center">
                <h3 class="page-title mb-0 p-0">Kerusakan</h3>
                <div class="d-flex align-items-center">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Kerusakan</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <div class="row">
            <!-- column -->
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Form Tambah Kerusakan</h4>
                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <strong>Whoops!</strong> There where some problems with your input.<br><br>
                                    <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                    </ul>
                                </div>
                            @endif
                            <div class="form">
                                <form class="form-validate form-horizontal" id="kerusakan"
                                action="{{ isset($kerusakan) ? route('admin.kerusakan.update',$kerusakan->id) : route('admin.kerusakan.store') }}" method="post">
                                {!! csrf_field() !!}
                                {!! isset($kerusakan) ? method_field('PUT') : '' !!}
                                <input type="hidden" name="id" value="{{ isset($kerusakan) ? $kerusakan->id : ''}}">
                                <div class="form-group">
                                    <label for="cname" class="control-label col-lg-2">Kategori<span class="require">*</span></label>
                                    <div class="col-lg-10">
                                    <select name="category_id" id="category_id" class="form-control" @error('category_id') is-invalid @enderror" value="{{ old('category_id') }}">
                                        @foreach($categories as $category)
                                        <option value="{{ isset($category) ? $category->id : ''}}">{{$category->name}}</option>
                                        @endforeach
                                    </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="cname" class="control-label col-lg-2">Jenis Kerusakan<span class="require">*</span></label>
                                    <div class="col-lg-10">
                                    <input class="form-control" type="text" name="jenis_kerusakan" id="jenis_kerusakan" minlenght="5" value="{{ isset($kerusakan) ? $kerusakan->jenis_kerusakan : ''}}" require />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="cname" class="control-label col-lg-2">Harga<span class="require">*</span></label>
                                    <div class="col-lg-10">
                                    <input class="form-control" type="text" name="harga" id="harga" minlenght="5" value="{{ isset($kerusakan) ? $kerusakan->harga : ''}}" require />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-lg-offset-2 col-lg-10">
                                    <button class="btn btn-primary" type="submit">Submit</button>
                                    <a href="{{ route('admin.kerusakan.index') }}"><button class="btn btn-default" type="button">Cancel</button></a>
                                    </div>
                                </div>
                                </form>
                            </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End PAge Content -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Container fluid  -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
</div>
<!-- ============================================================== -->
<!-- End Page wrapper  -->
@endsection

YOOVIS/resources/views/backend/kerusakan/index.blade.php
@extends('backend/layouts.template')
@section('content')
<!--main content start-->
<div class="page-wrapper">
  <!-- ============================================================== -->
  <!-- Bread crumb and right sidebar toggle -->
  <!-- ============================================================== -->
  <div class="page-breadcrumb">
    <div class="row align-items-center">
      <div class="col-md-6 col-8 align-self-center">
        <h3 class="page-title mb-0 p-0">Kerusakan</h3>
        <div class="d-flex align-items-center">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">Kerusakan</li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </div>
  <!-- ============================================================== -->
  <!-- End Bread crumb and right sidebar toggle -->
  <!-- ============================================================== -->
  <!-- ============================================================== -->
  <!-- Container fluid  -->
  <!-- ============================================================== -->
  <div class="container-fluid">
      <!-- ============================================================== -->
      <!-- Start Page Content -->
      <!-- ============================================================== -->
      <div class="row">
          <!-- column -->
          <div class="col-sm-12">
              <div class="card">
                  <div class="card-body">
                      <h4 class="card-title">Tabel Karusakan</h4>
                      <div class="panel-body">
                        @if ($message = Session::get('success'))
                          <div class="alert alert-success">
                            <p>{{ $message }}</p>
                          </div>
                        @endif
                        <a href="{{ route('admin.kerusakan.create') }}">
                          <button class="btn btn-primary" type="button"><i class="fa fa-plus"> Tambah</i></button>
                        </a><br><br>
                      <div class="table-responsive">
                        <table class="table table-striped table-advance table-hover">
                          <tbody>
                            <tr>
                              <th><i class="icon_briefcase"></i> Jenis Kerusakan</th>
                              <th><i class="icon_briefcase"></i> Kategori</th>
                              <th><i class="icon_briefcase"></i> Harga</th>
                              <th><i class="icon_cogs"></i> Action</th>
                            </tr>
                            @foreach ($kerusakan as $row)
                              <tr>
                                <td>{{$row->jenis_kerusakan}}</td>
                                <td>{{$row->category->name}}</td>
                                <td>{{$row->harga}}</td>
                                <td>
                                  <div class="btn-group">
                                    <form action="{{ route('admin.kerusakan.destroy', $row->id)}}" method="POST">
                                      <a href=" {{ route('admin.kerusakan.edit' ,$row->id) }} " class="btn btn-warning"><i class="fa fa-edit"></i></a>
                                      @csrf
                                      @method('DELETE')
                                      <button type="submit" class="btn btn-danger" name="button"
                                      onclick="return confirm('Apakah anda yakin menghapus data ini ?')">
                                        <i class="fa fa-trash"></i>
                                      </button>
                                    </form>
                                  </div>
                                </td>
                              </tr>
                            @endforeach
                          </tbody>
                        </table>
                      </div>
                  </div>
              </div>
          </div>
      </div>
      <!-- ============================================================== -->
      <!-- End PAge Content -->
      <!-- ============================================================== -->
      <!-- ============================================================== -->
      <!-- Right sidebar -->
      <!-- ============================================================== -->
      <!-- .right-sidebar -->
      <!-- ============================================================== -->
      <!-- End Right sidebar -->
      <!-- ============================================================== -->
  </div>
  <!-- ============================================================== -->
  <!-- End Container fluid  -->
  <!-- ============================================================== -->
  <!-- ============================================================== -->
</div>
<!-- ============================================================== -->
<!-- End Page wrapper  -->
@endsection